### ISSUE TITLE
Create base images

### ISSUE THREAD

**Issue by danisla** [selkies-project/selkies-gstreamer#15]
To make this project easier to build on top of, create some base images for various use cases. The `Dockerfile.example` has many of the dependencies codified, but more purpose based images would be ideal.

## Images Proposal

Base Images:
- `images/ubuntu/base`: image with most of the system dependencies needed to use the software encoder with xvfb. Includes gstreamer, gst-web,  python app, and entrypoint script. Dockerfile should be parameterized for both Ubuntu 18.04 and 20.04.
- `images/ubuntu/gpu`: starts from `base` image and adds cuda libraries to support GPU accelerated encoding with NVENC.
- `images/ubuntu/glx`: starts from `gpu` image and adds support for hardware accelerated GLX with integrated X11 server.
- `images/ubuntu/vgl`: starts from `gpu` image and add support for off-screen rendering with VGL using EGL DRI method.

Example Images:
- `images/examples/minimal-desktop`: example image similar to the current Dockerfile.example, installs basic window manager and desktop experience. Parameterize Dockerfile with variants for the various base images.
- `images/examples/gnome-desktop`: example image with gnome desktop and HiDPI support. 
- `images/examples/xfce-desktop`: example image with xfce desktop and HiDPI support.

## Entrypoint
It should be relatively simple for users to integrate the base image in their own projects.

The python app and all of it's dependencies (like pulseaudio) should run in the background.

Some options:
- entrypoint wrapper script (like the selkies-vdi app streaming images do today)
- supervisord
- systemd (only supported on sysbox runtime)

**Comment by ehfd** [comment]
I guess these two containers cover most of what is required for glx and vgl, and is intended to be used as a base containers for adding more applications in.
https://github.com/ehfd/docker-nvidia-egl-desktop
https://github.com/ehfd/docker-nvidia-glx-desktop

**Comment by ehfd** [comment]
> Do you have the side effects of Xfce and GNOME in a container documented somewhere, or would you be willing to help document them? It would be nice to show examples with multiple DEs and document their side-effects and tradeoffs. Ubuntu Mate is pretty heavy compared to other desktop environments which increases the image size significantly so I don't want that to be the only option.

Xfce is light if full desktop (xubuntu-desktop) is not being used. MATE is lighter in ubuntu-mate-desktop because the DE shares GTK+ libraries with utility packages whereas Xfce does not. However, there was something in xubuntu-desktop that kept dumping cores, whereas MATE was OK if I removed the bluetooth packages manually. One thing that I additionally did not like about Xfce was that there was no reliable way to change the skin using the command line, whereas MATE has a good interface by default. For GNOME 3, lots of stuffs seem to be broken, where the largest issue is that it resizes the screen on its own to an incorrect resolution when there is no EDID. x11docker also does not support GNOME 3 confidently, which is another thing that showcases that GNOME inside a container is not trivial to implement with minimal configuration so far.

I just left a link up there if anyone wants a full desktop environment, which requires assessing various utility packages for functionality. You are also the author of the Dockerfile configuration portions of selkies-gstreamer for our container, so it's at your discretion for deciding how the base packages would be. I'll change the license of my containers to GPL for convenience as well soon.

**Comment by ehfd** [comment]
So far:

`images/ubuntu/base`: I polished it. But should add required packages including mesa's Vulkan and VA drivers for VAAPI in the future.
`images/ubuntu/gpu`: This is basically the same thing as base except the base image should be cudagl.
`images/ubuntu/vgl`: Install virtualgl, and use `vglrun +wm` to invoke the desktop environment. Same otherwise to gpu.
`images/ubuntu/glx`: Now, this gets complicated. Should start from gpu and modify my entrypoint.sh.

`images/examples/minimal-desktop`: Xfce IS our minimal desktop right now. Combine with xfce-desktop.
`images/examples/gnome-desktop`: This is buggy when a real monitor, and thus a real EDID, does not exist. Also, its reliance on systemd makes it extremely inadequate for containers.

LXDE, MATE, Xfce, LXQt, Lumina, Enlightenment, and some others are the only adequate DEs for containers.

GNOME and KDE will eventually be usable in Wayland, but I really don't recommend going for either now.

https://github.com/mviereck/x11docker#desktop-environments

**Comment by ehfd** [comment]
Closing this issue as docker-nvidia-glx-desktop and docker-nvidia-egl-desktop are now Selkies projects, and it's possible to integrate VirtualGL into the example container pretty easilly.
