### ISSUE TITLE
peer_id isn't defined, shouldn't 'uid' be used instead

### ISSUE THREAD

**Issue by callTx** [selkies-project/selkies-gstreamer#27]
https://github.com/selkies-project/selkies-gstreamer/blob/007cc1ef89a4cf161a06c8127d568491fe49ef6d/src/selkies_gstreamer/signalling_web.py#L321

**Comment by ehfd** [comment]
I don't really understand this issue. Could you elaborate whether this is a problem or not?

**Comment by callTx** [comment]
The peer_id in this line hasn't any definition. I was debugging the code and see came across this. So if I'm wrong you can close the issue.

**Comment by ehfd** [comment]
Oh, oh yes...
I think I understand what is the issue here
https://github.com/selkies-project/selkies-gstreamer/blob/master/src/selkies_gstreamer/signalling_web.py#L321
https://github.com/selkies-project/selkies-gstreamer/blob/master/src/selkies_gstreamer/signalling_web.py#L432

@danisla Is this section actually executed? If so, it does look weird on why peer_id is over there.

**Comment by ehfd** [comment]
@callTx This is dead code, and the interpreter will never run that section.
But in case we do need to use the room functionality in the distant future, we can take note of it.
Thank you for pointing that out, however.

**Comment by ehfd** [comment]
Relevant code: https://github.com/selkies-project/selkies-gstreamer/blob/master/src/selkies_gstreamer/signalling_web.py
Should be addressed with #39.

**Comment by callTx** [comment]
It appears to be working, but I'm not sure what effect it will have on the
rest of the project.

Em ter., 26 de abr. de 2022 às 08:21, Seungmin Kim ***@***.***>
escreveu:

**Comment by ehfd** [comment]
Deserves a rewrite of the signaling server.

**Comment by ehfd** [comment]
We will rewrite the signaling server in #39. But for now, this issue doesn't have direct implications for 1-to-1 WebRTC communication.
